# Generated by Django 3.2.4 on 2021-07-09 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetups', '0004_auto_20210708_2050'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetup',
            name='date',
            field=models.DateTimeField(auto_now_add=True, auto_now=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='meetup',
            name='organizer',
            field=models.EmailField(default='', max_length=200, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='meetup',
            name='participants',
            field=models.ManyToManyField(blank=True, null=True, to='meetups.Participant'),
        ),
    ]
