# Generated by Django 3.2.4 on 2021-07-09 04:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meetups', '0008_auto_20210708_2131'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meetup',
            old_name='organizer',
            new_name='organizer_email',
        ),
        migrations.RenameField(
            model_name='organizer',
            old_name='username',
            new_name='name',
        ),
    ]
